#PROGRAM TO PERFORM ALL ARITHMETIC OPERATIONS
a = int(input("Enter first number:"))
b = int(input("Enter second number:"))
print("Arthimetic operators")
print("Addition : ",a+b)
print("Subtraction : ",a-b)
print("Multiplication : ",a*b)
print("Division : ",a/b)
print("Modulus : ",a%b)
print("Exponential power : ",a**2)
